apiVersion: policies.kubewarden.io/v1alpha2
kind: PolicyServer
metadata:
  name: default
spec:
  image: ghcr.io/kubewarden/policy-server:latest@sha256:4d8e85e830b092f84a1005429077d0987945ca27324d97b6e90994730876605d
  replicas: 1
  serviceAccountName: policy-server
  env:
  - name: KUBEWARDEN_LOG_LEVEL
    value: debug
