name: Bug from web gui
description: File a bug originating from the web gui
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: searched-existing-issues
    attributes:
      label: Is there an existing issue for this?
      description: Please [search](https://github.com/appvia/psp-migration/issues) to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: checkboxes
    id: engines
    attributes:
      label: What policy engine(s) are you using?
      description: You may select more than one.
      options:
        - label: Kynevro
        - label: Kubewarden
        - label: Gatekeeper

  - type: textarea
    id: input
    attributes:
      label: Input PSP
      render: yaml

  - type: textarea
    id: gatekeeper-yaml
    attributes:
      label: gatekeeper output
      render: yaml

  - type: textarea
    id: kubewarden-yaml
    attributes:
      label: kubewarden output
      render: yaml

  - type: textarea
    id: kynvero-yaml
    attributes:
      label: kynvero output
      render: yaml
