name: Bug from web gui
description: File a bug originating from the web gui
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: checkboxes
    id: engine
    attributes:
      label: What policy engine were you generating policy for?
      options:
        - label: Gatekeeper
        - label: Kynvero
        - label: Kubewarden
  - type: textarea
    id: input
    attributes:
      label: Input PSP
      render: yaml

  - type: textarea
    id: gatekeeper
    attributes:
      label: gatekeeper output
      render: yaml

  - type: textarea
    id: kubewarden
    attributes:
      label: kubewarden output
      render: yaml

  - type: textarea
    id: kynvero
    attributes:
      label: kynvero output
      render: yaml
