name: Auto approve renovate
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'renovate[bot]' || github.actor == 'chrisns'
    steps:
      - uses: hmarr/auto-approve-action@v3
