name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        system: 
          - psp
          # - pss
          - gatekeeper

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - if: matrix.system == 'psp'
        name: Create kind cluster for PSP
        uses: container-tools/kind-action@v1.7.0
        timeout-minutes: 5
        with: 
          kubectl_version: v1.22.2
          cluster_name: kind-${{matrix.system}}
          registry: false
          config: tests/kind-config.yaml

      - if: matrix.system == 'gatekeeper'
        name: Create kind cluster for gatekeeper
        uses: container-tools/kind-action@v1.7.0
        timeout-minutes: 5
        with: 
          kubectl_version: v1.22.2
          cluster_name: kind-${{matrix.system}}
          registry: false

      - if: matrix.system == 'gatekeeper'
        name: Install gatekeeper
        run: |
          kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.5/deploy/gatekeeper.yaml
          kubectl wait --for=condition=available --timeout=600s  -n gatekeeper-system \
            deployment/gatekeeper-audit \
            deployment/gatekeeper-controller-manager
          kubectl apply -k submodules/gatekeeper-library/library/pod-security-policy
          sleep 10 # @TODO: make a wait

      - name: BATS tests
        run: submodules/bats/bin/bats tests
        env:
          SYSTEM: ${{ matrix.system }}

      - name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: Test results        
          path: report.xml
          reporter: java-junit