name: JS build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    paths:
      - src/**
      - "*.json"
      - ".nvmrc"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - uses: actions/setup-node@v2.5.0
        with:
          node-version-file: '.nvmrc'
      - run: npm install
      - run: node_modules/.bin/jest --json --outputFile=result.json --testLocationInResults
      - uses: tanmen/jest-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build

      - uses: actions/upload-artifact@v2.3.0
        with:
          name: psp-migration-alpine-arm64
          path: dist/bin/psp-migration-alpine-arm64
      - uses: actions/upload-artifact@v2.3.0
        with:
          name: psp-migration-alpine-x64
          path: dist/bin/psp-migration-alpine-x64

      - uses: actions/upload-artifact@v2.3.0
        with:
          name: psp-migration-linux-arm64
          path: dist/bin/psp-migration-linux-arm64
      - uses: actions/upload-artifact@v2.3.0
        with:
          name: psp-migration-linux-x64
          path: dist/bin/psp-migration-linux-x64

      - uses: actions/upload-artifact@v2.3.0
        with:
          name: psp-migration-linuxstatic-arm64
          path: dist/bin/psp-migration-linuxstatic-arm64
      - uses: actions/upload-artifact@v2.3.0
        with:
          name: psp-migration-linuxstatic-x64
          path: dist/bin/psp-migration-linuxstatic-x64

      - uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2
      - uses: actions/upload-artifact@v2.3.0
        with:
          name: psp-migration-macos-arm64
          path: dist/bin/psp-migration-macos-arm64
      - uses: actions/upload-artifact@v2.3.0
        with:
          name: psp-migration-macos-x64
          path: dist/bin/psp-migration-macos-x64

      - uses: actions/upload-artifact@v2.3.0
        with:
          name: psp-migration-win-arm64
          path: dist/bin/psp-migration-win-arm64

      - uses: actions/upload-artifact@v2.3.0
        with:
          name: psp-migration-win-x64
          path: dist/bin/psp-migration-win-x64