name: JS build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - uses: dorny/paths-filter@v2.10.2
        id: changes
        with:
          filters: |
            js:
              - src/**
              - "*.json"
              - ".nvmrc"

      - uses: actions/setup-node@v2.5.0
        if: steps.changes.outputs.js == 'true'
        with:
          node-version-file: '.nvmrc'
      - run: npm install
        if: steps.changes.outputs.js == 'true'
      - run: node_modules/.bin/jest --json --outputFile=result.json --testLocationInResults
        if: steps.changes.outputs.js == 'true'
      - uses: tanmen/jest-reporter@v1
        if: steps.changes.outputs.js == 'true' && always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build
        if: steps.changes.outputs.js == 'true'

      - uses: actions/upload-artifact@v2.3.1
        if: steps.changes.outputs.js == 'true'
        with:
          name: psp-migration-alpine-arm64
          path: dist/bin/psp-migration-alpine-arm64
      - uses: actions/upload-artifact@v2.3.1
        if: steps.changes.outputs.js == 'true'
        with:
          name: psp-migration-alpine-x64
          path: dist/bin/psp-migration-alpine-x64

      - uses: actions/upload-artifact@v2.3.1
        if: steps.changes.outputs.js == 'true'
        with:
          name: psp-migration-linux-arm64
          path: dist/bin/psp-migration-linux-arm64
      - uses: actions/upload-artifact@v2.3.1
        if: steps.changes.outputs.js == 'true'
        with:
          name: psp-migration-linux-x64
          path: dist/bin/psp-migration-linux-x64

      - uses: actions/upload-artifact@v2.3.1
        if: steps.changes.outputs.js == 'true'
        with:
          name: psp-migration-linuxstatic-arm64
          path: dist/bin/psp-migration-linuxstatic-arm64
      - uses: actions/upload-artifact@v2.3.1
        if: steps.changes.outputs.js == 'true'
        with:
          name: psp-migration-linuxstatic-x64
          path: dist/bin/psp-migration-linuxstatic-x64

      - uses: actions/upload-artifact@v2.3.1
        if: steps.changes.outputs.js == 'true'
        with:
          name: psp-migration-win-arm64
          path: dist/bin/psp-migration-win-arm64
      - uses: actions/upload-artifact@v2.3.1
        if: steps.changes.outputs.js == 'true'
        with:
          name: psp-migration-win-x64
          path: dist/bin/psp-migration-win-x64

      - uses: MOZGIII/install-ldid-action@v1
        if: steps.changes.outputs.js == 'true'
        with:
          tag: v2.1.5-procursus2
      - uses: actions/upload-artifact@v2.3.1
        if: steps.changes.outputs.js == 'true'
        with:
          name: psp-migration-macos-arm64
          path: dist/bin/psp-migration-macos-arm64
      - uses: actions/upload-artifact@v2.3.1
        if: steps.changes.outputs.js == 'true'
        with:
          name: psp-migration-macos-x64
          path: dist/bin/psp-migration-macos-x64