name: Web UI
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  webpublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-node@v2.5.0
        with:
          node-version-file: '.nvmrc'
      - run: npm install

      - run: npm run build

      - uses: actions/upload-artifact@v2.3.1
        with:
          name: dist
          path: dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
